### ISSUE TITLE
How can I diff two files from within a Go program?

### ISSUE THREAD

**Issue by secretuser1** [daviddengcn/go-diff#5]
I have two files:

f1 has the string 
```
hi how are you
```

f2 has the string
```
hi how are you ?
im good thanks
bye
```

I imported your library in my go program 

> import godiff "github.com/daviddengcn/go-diff/cmd"

I then ran the command after reading the file contents using `ioutil.ReadFile` function

> godiff.Exec(string(f1), string(f2), godiff.Options{})

The output does not show the difference properly though..I see something like 

```
Difference between hi how are you
 and hi how are you ?
im good thanks
bye
 ...
```

What am I missing?

**Comment by secretuser1** [comment]
Nevermind. It was a stupid mistake on my part. Instead of comparing two files, I was trying to read the contents into a string and then trying to compare them. It works just fine! Thanks a lot for this library :)

**Comment by dmitshur** [comment]
This `go-diff` library is primarily for comparing .go files, not just plain text. If you want to compare plain text only, you should use a general text diff library such as [`github.com/pmezard/go-difflib/difflib`](https://godoc.org/github.com/pmezard/go-difflib/difflib).
